test_upper_case_names (__main__.TestExercice) ... ERROR

======================================================================
ERROR: test_upper_case_names (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 17, in test_upper_case_names
    output = list(map(exercice.majuscule, self.words))
  File "/home/runner/work/c02-ch2-majuscule-RaphaelSalvas/c02-ch2-majuscule-RaphaelSalvas/exercice.py", line 7, in majuscule
    uni
NameError: name 'uni' is not defined

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
